await location.replace(
// "https://untappd.com/brouwerijpalm/beer"
// "https://untappd.com/AntiFactory/beer"
// "https://untappd.com/Scheldebrouwerij/beer"
// "https://untappd.com/w/abbaye-de-leffe/5/beer"
// "https://untappd.com/Omervanderghinste/beer"
// "https://untappd.com/BrasserieLefebvre/beer"
// "https://untappd.com/w/schloss-eggenberg/1115/beer"
// "https://untappd.com/PrairieArtisanAles/beer"
// "https://untappd.com/Selfmade_Brewery/beer"
// "https://untappd.com/brewdogbrewery/beer"
// "https://untappd.com/RochefortTrappist/beer"
// "https://untappd.com/BrouwerijDeHalveMaan/beer"
// "https://untappd.com/BVBrewery/beer"
// "https://untappd.com/Saldens/beer"
// "https://untappd.com/SteppeNwind/beer"
// "https://untappd.com/Brewlokbrewery/beer"
// "https://untappd.com/Ta-Ta/beer"
// "https://untappd.com/SeagullOleg/beer"
// "https://untappd.com/VelkaMorava/beer"
// "https://untappd.com/Zavodbrewery/beer"
    // "https://untappd.com/MainRule/beer"
    // "https://untappd.com/brasserieatrium/beer"
    // "https://untappd.com/HorrorBrewing/beer"
    // "https://untappd.com/BrouwerijKees/beer"
    // "https://untappd.com/CosmicCityBrew/beer"
    // "https://untappd.com/w/dingslebener-privatbrauerei-metzler/26594/beer"
    // "https://untappd.com/dietabrewery/beer"
    // "https://untappd.com/ZagovorBrewery/beer"
    // "https://untappd.com/RustiquePivasique/beer"
    // "https://untappd.com/struise/beer"
    // "https://untappd.com/Affligem/beer"
    "https://untappd.com/PlagueBrew/beer"
)

// [
//     "https://untappd.com/BakuninBrewery/beer",
//     "https://untappd.com/w/staatliches-hofbrauhaus-munchen/5566/beer",
//     "https://untappd.com/JawsBrew/beer",
//     "https://untappd.com/Plan_B_Brewery/beer",
//     "https://untappd.com/TrappistWestmalle/beer",
//     "https://untappd.com/Atmosphere_Brewery/beer"
// ]
